cache: yarn
stages:
  - name: test
    if: type = pull_request AND tag IS blank
install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - nvm install 14
  - npm i -g npm@8
  - npm i
jobs:
  include:
    - stage: test
      language: node_js
      node_js: '14'
      script:
        - nx run-many --target lint --all
        - nx run-many --target test --all
        - commitlint-travis
