cache: npm
stages:
  - name: code-quality
    if: type = pull_request AND tag IS blank

install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - npm install -g npm@8
  - npm ci

jobs:
  include:
    - stage: code-quality
      language: node_js
      node_js: '14'
      script:
        - commitlint-travis

    - stage: code-quality
      language: node_js
      node_js: '14'
      script:
        - npm run lint:all

    - stage: code-quality
      language: node_js
      node_js: '14'
      script:
        - npm run test:all

    - stage: code-quality
      language: node_js
      node_js: '14'
      script:
        - npm run build:all
