language: node_js
node_js: '14'

cache: npm
stages:
  - name: code-quality
    if: type = pull_request AND tag IS blank

install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - npm install -g npm@8
  - npm ci

jobs:
  include:
    - stage: code-quality
      script:
        - commitlint-travis

    - stage: code-quality
      script:
        - npm run format:check

    - stage: code-quality
      script:
        - npm run lint:all

    - stage: code-quality
      script:
        - npm run test:all

    - stage: code-quality
      script:
        - npm run build:all

    - stage: code-quality
      script:
        - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - NODE_OPTIONS=--max-old-space-size=8192 npx nx run-many --target build --all --configuration development
